"""Minimal self-contained HTML report renderer (no external deps)."""

from __future__ import annotations

import html
from pathlib import Path
from typing import Any


SEV_CLASS = {
    "critical": "sev-critical",
    "high": "sev-high",
    "medium": "sev-medium",
    "moderate": "sev-medium",
    "low": "sev-low",
    "info": "sev-low",
}

STYLE = """
body { font: 14px/1.45 -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       background: #0f1117; color: #d7d7d7; margin: 0; padding: 0; }
.container { max-width: 960px; margin: 2rem auto; padding: 0 1.5rem; }
h1 { color: #fff; border-bottom: 1px solid #333; padding-bottom: 0.5rem; }
.meta { color: #888; font-size: 0.9rem; }
.finding { border: 1px solid #2a2d34; border-radius: 6px; padding: 1rem 1.25rem;
           margin: 1rem 0; background: #15181f; }
.finding h2 { margin: 0 0 0.5rem; font-size: 1.1rem; color: #fff; }
.badge { display: inline-block; padding: 2px 8px; border-radius: 999px;
         font-size: 0.75rem; margin-right: 0.5rem; vertical-align: middle; }
.sev-critical { background: #6b1818; color: #ffa0a0; }
.sev-high     { background: #753f0a; color: #ffcf8f; }
.sev-medium   { background: #3d3e15; color: #e8e59a; }
.sev-low      { background: #184f24; color: #a6e3b5; }
.evidence { background: #0b0d13; padding: 0.75rem; border-radius: 4px;
            font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
            font-size: 0.85rem; white-space: pre-wrap; overflow-x: auto; color: #b5b5b5; }
footer { color: #666; font-size: 0.8rem; text-align: center; margin-top: 3rem; }
"""


def render_html(findings: list[dict[str, Any]], run_dir: Path, run_id: str) -> str:
    parts = [
        "<!doctype html>",
        "<html lang=\"en\"><head><meta charset=\"utf-8\">",
        f"<title>strix report {html.escape(run_id)}</title>",
        f"<style>{STYLE}</style></head><body><div class=\"container\">",
        f"<h1>strix report · {html.escape(run_id)}</h1>",
        f"<div class=\"meta\">Run directory: {html.escape(str(run_dir))} · "
        f"{len(findings)} finding(s)</div>",
    ]
    for f in findings:
        sev = (f.get("severity") or "info").lower()
        badge = SEV_CLASS.get(sev, "sev-low")
        title = html.escape(str(f.get("title") or f.get("id") or "Unnamed finding"))
        desc = html.escape(str(f.get("description") or ""))
        evidence = html.escape(str(f.get("evidence") or f.get("proof_of_concept") or ""))
        location = html.escape(str(f.get("file") or f.get("location") or ""))
        parts.append(f"<div class=\"finding\">")
        parts.append(f"<h2><span class=\"badge {badge}\">{html.escape(sev)}</span>{title}</h2>")
        if location:
            parts.append(f"<div class=\"meta\">Location: {location}</div>")
        if desc:
            parts.append(f"<p>{desc}</p>")
        if evidence:
            parts.append(f"<pre class=\"evidence\">{evidence}</pre>")
        parts.append("</div>")
    parts.append(
        "<footer>Generated by strixnoapi — hardened fork of "
        "<a style='color:#888' href='https://github.com/usestrix/strix'>usestrix/strix</a></footer>"
    )
    parts.append("</div></body></html>")
    return "\n".join(parts)
